apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
  labels:
    purpose: housekeeping
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: busybox
        command: 
        - "echo"
        - "running clean up job now."
      restartPolicy: "Never"