# This sample manifest file illustrates injecting environment variables
# by directly defining them in the manifest file as well as referencing 
# the config map to populate the values

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-env-mix
data:
  environmentVar3: "cm-env_var_3"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env
  labels:
    type: app
    feature: env-mix-definition
spec:
  containers:
  - name: nginx-with-env
    image: prathameshkavlekar/sw-quotes-service
    env:
    - name: ENV_1
      value: "env_var_1"
    - name: ENV_2
      value: "env_var_2"
    - name: ENV_3
      valueFrom:
        configMapKeyRef:
          name: cm-env-mix
          key: "environmentVar3"
